P21_FluentValidation
drenhaziri/Postieri pull request #28
Opened 2022-09-05 09:06 UTC by Ibadetegashi

2022-09-13 13:33 UTC, dren-haziri requested changes

2022-09-13 13:33 UTC, dren-haziri commented on Postieri/Validators/ShelfValidator.cs
> +
Remove this

2022-09-13 13:33 UTC, dren-haziri commented on Postieri/Validators/ShelfValidator.cs
>              RuleFor(x => x.MaxProducts).NotEmpty().NotNull().GreaterThanOrEqualTo(0).WithMessage(" {PropertyName} shoud be a positive number!");
remove context

2022-09-13 13:39 UTC, Ibadetegashi commented on Postieri/Validators/ShelfValidator.cs
>              RuleFor(x => x.MaxProducts).NotEmpty().NotNull().GreaterThanOrEqualTo(0).WithMessage(" {PropertyName} shoud be a positive number!");
ok

2022-09-14 12:37 UTC, dren-haziri approved these changes

2022-09-14 12:42 UTC, merged