P27_Refactor_RoleModule refactored role module
drenhaziri/Postieri pull request #39
Opened 2022-09-13 21:31 UTC by ibrahimejupi614

P27_Refactor_RoleModule refactored role module

2022-09-14 06:58 UTC, dren-haziri requested changes

2022-09-14 06:58 UTC, dren-haziri commented on Postieri/Controllers/RolesController.cs
>          {
`DataContext` goes to the service.

2022-09-14 11:42 UTC, dren-haziri requested changes

2022-09-14 11:42 UTC, dren-haziri commented on Postieri/Interfaces/IRolesService.cs
>      }
`AddRole`, `UpdateRole` and `DeleteRole` need to be `bool`. Be consistent with params naming though, `role` or `request` for every method role parameter. I also suggest creating `Exists` method to use when dealing with crud.

2022-09-14 12:40 UTC, dren-haziri requested changes
Create `Exists` method and use it on crud to verify if a role exists before adding a new one, updating or deleting

2022-09-14 12:41 UTC, ibrahimejupi614 commented
> Create `Exists` method and use it on crud to verify if a role exists before adding a new one, updating or deleting

Ok

2022-09-15 14:25 UTC, dren-haziri approved these changes

2022-09-15 14:25 UTC, merged